<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>SecurePort.Configuration</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SecurePort.Core\SecurePort.Core.csproj" />
    <ProjectReference Include="..\SecurePort.Storage\SecurePort.Storage.csproj" />
  </ItemGroup>

</Project>
