using System.Text;
using SecurePort.Core.Enums;
using SecurePort.Core.Interfaces;
using SecurePort.Core.Models;

namespace SecurePort.Reports.Generators;

/// <summary>
/// Generates readable plain-text reports from scan session data.
/// Maintains proper alignment and is readable on any operating system.
/// </summary>
public sealed class TxtReportGenerator : IReportGenerator
{
    private const int ColumnWidth = 16;
    private const int SeparatorWidth = 80;

    /// <inheritdoc />
    public async Task<string> GenerateReportAsync(ScanSession session, ExportOptions options, CancellationToken ct)
    {
        ArgumentNullException.ThrowIfNull(session);
        ArgumentNullException.ThrowIfNull(options);

        var bytes = await GenerateReportBytesAsync(session, options, ct);
        var directory = Path.GetDirectoryName(options.FilePath);

        if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
        {
            Directory.CreateDirectory(directory);
        }

        await File.WriteAllBytesAsync(options.FilePath, bytes, ct);
        return options.FilePath;
    }

    /// <inheritdoc />
    public Task<byte[]> GenerateReportBytesAsync(ScanSession session, ExportOptions options, CancellationToken ct)
    {
        ArgumentNullException.ThrowIfNull(session);
        ArgumentNullException.ThrowIfNull(options);

        ct.ThrowIfCancellationRequested();

        var text = BuildReport(session, options);
        var bytes = Encoding.UTF8.GetBytes(text);
        return Task.FromResult(bytes);
    }

    /// <inheritdoc />
    public string GetFileExtension(ExportFormat format) => format switch
    {
        ExportFormat.TXT => ".txt",
        _ => throw new ArgumentException($"Unsupported export format: {format}", nameof(format))
    };

    private static string BuildReport(ScanSession session, ExportOptions options)
    {
        var sb = new StringBuilder();

        AppendHeader(sb);
        sb.AppendLine();

        AppendSection(sb, "SCAN INFORMATION");
        AppendKeyValue(sb, "Session ID", session.Id.ToString("D"));
        AppendKeyValue(sb, "Status", session.Status.ToString());
        AppendKeyValue(sb, "Start Time", session.StartTime.ToString("yyyy-MM-dd HH:mm:ss UTC"));
        AppendKeyValue(sb, "End Time", session.EndTime?.ToString("yyyy-MM-dd HH:mm:ss UTC") ?? "N/A");
        AppendKeyValue(sb, "Duration", session.Duration?.ToString(@"hh\:mm\:ss\.fff") ?? "N/A");
        sb.AppendLine();

        AppendSection(sb, "TARGET INFORMATION");
        AppendKeyValue(sb, "Host", session.Target.Host);
        AppendKeyValue(sb, "Port Range", $"{session.Target.PortStart} - {session.Target.PortEnd}");
        AppendKeyValue(sb, "Protocol", session.Target.Protocol.ToString());
        AppendKeyValue(sb, "Scan Type", session.Target.ScanType.ToString());
        AppendKeyValue(sb, "Timeout", session.Target.Timeout.ToString());
        AppendKeyValue(sb, "Max Concurrent", session.Target.MaxConcurrentConnections.ToString());
        sb.AppendLine();

        AppendSection(sb, "STATISTICS");
        AppendKeyValue(sb, "Total Ports Scanned", session.TotalPortsScanned.ToString());
        AppendKeyValue(sb, "Open Ports", session.OpenPortsFound.ToString());
        AppendKeyValue(sb, "Closed Ports", session.ClosedPortsFound.ToString());
        AppendKeyValue(sb, "Filtered Ports", session.FilteredPortsFound.ToString());
        AppendKeyValue(sb, "Errors", session.ErrorsEncountered.ToString());
        sb.AppendLine();

        var results = options.IncludeClosedPorts
            ? session.Results
            : session.Results.Where(r => r.State != PortState.Closed).ToList();

        if (results.Count > 0)
        {
            AppendSection(sb, "PORT RESULTS");
            AppendResultsTable(sb, results, options);
            sb.AppendLine();
        }

        if (options.IncludeScanMetadata && !string.IsNullOrEmpty(session.ErrorMessage))
        {
            AppendSection(sb, "ERROR DETAILS");
            sb.AppendLine($"  {session.ErrorMessage}");
            sb.AppendLine();
        }

        AppendFooter(sb);

        return sb.ToString();
    }

    private static void AppendHeader(StringBuilder sb)
    {
        AppendSeparator(sb);
        sb.AppendLine("  SECUREPORT SCAN REPORT");
        AppendSeparator(sb);
        sb.AppendLine($"  Generated: {DateTimeOffset.UtcNow:yyyy-MM-dd HH:mm:ss UTC}");
        sb.AppendLine($"  Application: SecurePort v{Core.Constants.AppConstants.Version}");
        AppendSeparator(sb);
    }

    private static void AppendFooter(StringBuilder sb)
    {
        AppendSeparator(sb);
        sb.AppendLine($"  Report generated by SecurePort v{Core.Constants.AppConstants.Version}");
        sb.AppendLine($"  Generated at: {DateTimeOffset.UtcNow:yyyy-MM-dd HH:mm:ss UTC}");
        AppendSeparator(sb);
    }

    private static void AppendSection(StringBuilder sb, string sectionTitle)
    {
        sb.AppendLine($"  --- {sectionTitle} ---");
    }

    private static void AppendKeyValue(StringBuilder sb, string key, string value)
    {
        sb.AppendLine($"  {key,-20} {value}");
    }

    private static void AppendSeparator(StringBuilder sb)
    {
        sb.AppendLine(new string('=', SeparatorWidth));
    }

    private static void AppendResultsTable(StringBuilder sb, IReadOnlyList<ScanResult> results, ExportOptions options)
    {
        var header = $"  {"Port",-8} {"Proto",-6} {"State",-10} {"Service",-20} {"Response",-12}";
        if (options.IncludeTimestamps)
        {
            header += $" {"Scanned At",-20}";
        }

        sb.AppendLine(header);
        sb.AppendLine($"  {new string('-', SeparatorWidth - 2)}");

        foreach (var result in results)
        {
            var responseTime = result.ResponseTime?.TotalMilliseconds.ToString("F2") + "ms" ?? "N/A";
            var line = $"  {result.Port,-8} {result.Protocol,-6} {result.State,-10} {(result.ServiceName ?? "—"),-20} {responseTime,-12}";

            if (options.IncludeTimestamps)
            {
                line += $" {result.ScannedAt:yyyy-MM-dd HH:mm:ss}";
            }

            sb.AppendLine(line);
        }
    }
}
